# Generated by Django 4.0.3 on 2022-03-08 15:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(null=True, upload_to='hostprofile')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=85)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=85)),
                ('profile_image', models.ImageField(null=True, upload_to='vendorprofile')),
                ('city', models.CharField(max_length=85)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('description', models.TextField()),
                ('years_in_business', models.PositiveSmallIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='WeddingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_guests', models.PositiveSmallIntegerField()),
                ('max_guests', models.PositiveSmallIntegerField(null=True)),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VendorWeddingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddingapi.vendor')),
                ('wedding_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddingapi.weddingsize')),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='weddingapi.vendortype'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddingapi.host')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddingapi.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddingapi.host')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddingapi.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HostVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_hour', models.DecimalField(decimal_places=2, default=None, max_digits=7, null=True)),
                ('hired', models.BooleanField(default=False)),
                ('fired', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddingapi.host')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddingapi.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='wedding_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='weddingapi.weddingsize'),
        ),
    ]
