# Generated by Django 4.0.3 on 2022-03-08 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='wedding_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weddingapi.weddingsize'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weddingapi.vendortype'),
        ),
    ]
