# Generated by Django 4.0.3 on 2022-03-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapi', '0004_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='wedding_sizes',
            field=models.ManyToManyField(related_name='vendor_wedding_sizes', through='weddingapi.VendorWeddingSize', to='weddingapi.weddingsize'),
        ),
    ]
