# Generated by Django 4.0.3 on 2022-03-22 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapi', '0005_vendor_wedding_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color1', models.CharField(max_length=7)),
                ('color2', models.CharField(max_length=7)),
                ('color3', models.CharField(max_length=7)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddingapi.host')),
            ],
        ),
    ]
