# Generated by Django 4.0.3 on 2022-03-22 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapi', '0006_palette'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='visionphotos')),
                ('time_added', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddingapi.host')),
            ],
        ),
    ]
