# Generated by Django 4.0.3 on 2022-03-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapi', '0007_visionphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='exampleimages')),
                ('time_added', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddingapi.vendor')),
            ],
        ),
    ]
